# Generated by Django 4.1.8 on 2023-06-05 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=300)),
                ('link', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('PR', 'Purchased'), ('NOT', 'Not purchased')], default='NOT', max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.profile')),
            ],
        ),
    ]
