# Generated by Django 4.1.8 on 2023-06-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited', models.EmailField(max_length=30)),
                ('inviter', models.ManyToManyField(to='user.profile')),
            ],
        ),
    ]
