# Generated by Django 4.1.8 on 2023-06-05 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('invite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitationhistory',
            name='inviter',
        ),
        migrations.AddField(
            model_name='invitationhistory',
            name='inviter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='user.profile'),
        ),
    ]
